### ISSUE TITLE
Uh how do I put this on my server...

### ISSUE THREAD

**Issue by Tydium** [profsucrose/tetraft#1]
I am looking for a .jar file but im too stupid to understand that this is source code. So how do I apply it to my server. (step by step instruction please)

**Comment by profsucrose** [comment]
Ha I never expected anyone to actually want to use the plugin. 

The plugin is kind of a hack put together to make a playable Tetris game using a specific Minecraft world with a board set up at specific coordinates and whatnot. 

I'm working on some other stuff right now, but when I'm done with it I'll refactor the Tetris plugin to make it easily usable with servers using an automatically-generated game world. When this is done usage will be documented in the README.

**Comment by Tydium** [comment]
Oh alright no problem!
